services:
  db_postgres_didi_students:
    image: postgres
    container_name: db_postgres_didi_students
    restart: always
    ports:
      - 1234:5432
    env-file:
      - .env
    volumes:
      - pg_didi_students: /var/lib/postgresql/data

  node_app_didi_students:
    container_name: node_app_didi_students
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_didi_students
    env_file:
      - .env

volumes:
  pg_didi_students:
