services:
  db_postgres_students:
    image: postgres
    container-name: db_postgres_didi-students
    restart: always
    ports:
      - 1234:5432
    env-file:
      - .env
    volumes:
      - pg_didi-students: /var/lib/postgresql/data

  node_app_didi-students:
    container-name: node_app_didi-students
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_didi-students
    env_file:
      - .env

volumes:
  pg_didi-students:
